version: "3.8"

services:
  web:
    image: nginx:latest
    command: nginx -g 'daemon off;'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
    ports:
      - "9000:80"
    networks:
      - app-network

  manage:
    build:
      context: .
      dockerfile: Dockerfile.manage
    working_dir: /app
    environment:
      TZ: "Asia/Shanghai"
      DEBUG_MODE: "true"
    command: >
      streamlit run app_manage.py --server.port 9001 --server.address 0.0.0.0 --server.runOnSave true --server.fileWatcherType poll --browser.gatherUsageStats false
    volumes:
      - ./:/app
    ports:
      - "9001:9001"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.manage
    command: fastapi dev app_api.py --host 0.0.0.0 --port 9002
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "9002:9002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
